//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinKhaiBao
    {
        public int Id { get; set; }
        public string HoTenNguoiKhaiBao { get; set; }
        public string DiaChiNguoiKhaiBao { get; set; }
        public string NoiDungKhaiBao { get; set; }
        public string HoTenTre { get; set; }
        public string DiaChiTre { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<int> Tuoi { get; set; }
        public string ToChucTrinhBao { get; set; }
        public string ThongTinThem { get; set; }
        public string TrangThai { get; set; }
        public string SoDienThoai { get; set; }
    }
}
